name: hushhxtinder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+3

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg:
  image_picker:
  google_fonts: 6.1.0
  provider:
  supabase_flutter: ^2.0.0
  shared_preferences:
  geolocator:
  geocoding:
  firebase_core: ^3.4.0
  firebase_auth:
  firebase_storage:
  swipable_stack:
  flutter_image_compress: ^1.1.3
  uuid: ^4.5.0
  flutter_local_notifications: ^17.2.2
  http: ^1.2.2
  shimmer: ^3.0.0
  marquee_list: ^1.0.0
  file_picker: ^8.1.2
  pdfx: ^2.7.0
  syncfusion_flutter_pdf: ^24.2.9
  flutter_image: ^4.1.11
  sharpapi_flutter_client: ^1.2.0
  flutter_tilt: ^3.0.6
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  location: ^6.0.2
  go_router: ^14.2.8
  share_plus: ^10.0.2
  uni_links2: ^0.5.0
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/assets/.env
    - lib/assets/images/app_bg.jpeg
    - lib/assets/images/hush_logo.svg
    - lib/assets/images/instagram.png
    - lib/assets/images/link.png
    - lib/assets/images/linkedin.png
    - lib/assets/images/twitter.png
    - lib/assets/images/youtube.png
    - lib/assets/images/button.png
    - lib/assets/images/chat_nav.png
    - lib/assets/images/create_nav.png
    - lib/assets/images/explore_nav.png
    - lib/assets/images/home_nav.png
    - lib/assets/images/profile_nav.png
    - lib/assets/images/dislike.svg
    - lib/assets/images/heart.svg
    - lib/assets/images/reload.svg
    - lib/assets/images/spark.svg
    - lib/assets/images/star.svg
    - lib/assets/images/nopehushhconnect.png
    - lib/assets/images/likehushhconnect.png
    - lib/assets/images/notify_topbar.png
    - lib/assets/images/navbar_fifth.png
    - lib/assets/images/huash_logo_2.svg
    - lib/assets/images/facebook_svg.svg
    - lib/assets/images/instagram_svg.svg
    - lib/assets/images/linkedin_svg.svg
    - lib/assets/images/twitter_svg.svg
    - lib/assets/images/youtube_svg.svg
    - lib/assets/images/lookingforjob.jpeg
    - lib/assets/images/love.jpeg
    - lib/assets/images/movietime.jpeg
    - lib/assets/images/gym.jpeg
    - lib/assets/images/friends.jpeg
    - lib/assets/images/developers.jpeg
    - lib/assets/images/coffeedate.jpeg
    - lib/assets/images/Frame.png
    - lib/assets/images/grey_tick.png
    - lib/assets/images/arrow-down.png
    - lib/assets/images/arrow-up.png
    - lib/assets/images/super_like.png
    - lib/assets/images/filter.jpeg
    - lib/assets/flags/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
