// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-TTZmX3vK0HzPnPJQmFTwug-r6wlHGjs',
    appId: '1:884832724786:web:4d2211fbdc97f74636592b',
    messagingSenderId: '884832724786',
    projectId: 'hushhconnect-f3aac',
    authDomain: 'hushhconnect-f3aac.firebaseapp.com',
    storageBucket: 'hushhconnect-f3aac.appspot.com',
    measurementId: 'G-3EVCT73YTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcPTB6AlhSsejtRtj7oMP4Aj_XuzQCblM',
    appId: '1:884832724786:android:09e7fd8b9bd43c5036592b',
    messagingSenderId: '884832724786',
    projectId: 'hushhconnect-f3aac',
    storageBucket: 'hushhconnect-f3aac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9BDnUjXBDec8aIAbAmDB6zMYGr4aCgyE',
    appId: '1:884832724786:ios:44895f9c3d08a83d36592b',
    messagingSenderId: '884832724786',
    projectId: 'hushhconnect-f3aac',
    storageBucket: 'hushhconnect-f3aac.appspot.com',
    iosBundleId: 'com.example.hushhxtinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9BDnUjXBDec8aIAbAmDB6zMYGr4aCgyE',
    appId: '1:884832724786:ios:44895f9c3d08a83d36592b',
    messagingSenderId: '884832724786',
    projectId: 'hushhconnect-f3aac',
    storageBucket: 'hushhconnect-f3aac.appspot.com',
    iosBundleId: 'com.example.hushhxtinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-TTZmX3vK0HzPnPJQmFTwug-r6wlHGjs',
    appId: '1:884832724786:web:65b82fdcb02ebe7536592b',
    messagingSenderId: '884832724786',
    projectId: 'hushhconnect-f3aac',
    authDomain: 'hushhconnect-f3aac.firebaseapp.com',
    storageBucket: 'hushhconnect-f3aac.appspot.com',
    measurementId: 'G-5MW9S5W34R',
  );

}